# Generated by Django 4.1.4 on 2022-12-22 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_rename_author_author_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='user',
            new_name='author',
        ),
    ]
