# Generated by Django 4.1.4 on 2022-12-22 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_categoryuser_delete_categoryauthor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_author',
            new_name='author',
        ),
    ]
