# Generated by Django 4.1.4 on 2022-12-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_rename_post_author_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(related_name='posts', through='news.PostCategory', to='news.category'),
        ),
    ]
