# Generated by Django 4.1.4 on 2022-12-22 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_alter_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default='default cat', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='news.category'),
        ),
    ]
